name: FLUXNET_LPJGUESS
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython=8.8.0
  - ipywidgets=8.0.4
  - nb_conda_kernels=2.3.1
  - notebook=6.5.2
  - pandas=1.5.2
  - pip=22.3.1
  - python=3.10.8
  - r=4.1
  - r-base=4.1.3
  - r-devtools
  - r-dplyr
  - r-htmlTable
  - r-ggpubr
  - pip:
    - rpy2==3.5.7
    - https://github.com/MikkoVihtakari/ggOceanMaps

